# Generated by Django 4.2.13 on 2024-10-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.ImageField(upload_to='project_images/'),
        ),
    ]
